### ISSUE TITLE
Conventional Commits proposition

### ISSUE THREAD

**Issue by dominikmlynarczyk** [MFG-POS/mfg-pos#3]
I propose using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for future commits.
It will provide better search mechanism and standardized, semantic commit messages.
We can tinker default type & scoping for our project needs.

**Comment by mfurmanit** [comment]
We discussed the issue on the slack and agreed that we will be using conventional commits semantic in future commits.
